### PR TITLE
Added Hungarian translations

### PR DESCRIPTION
**Pull request by zoli111**

### CODE REVIEW

**Comment by tsujan** [comment]
You have translated several strings completely but haven't marked them as "finished" (in Qt Linguist). Is that intentional?

**Comment by zoli111** [comment]
> Is this intentional?
Yes, that is. I have only marked those in which I am absolutely sure that they are ready. The others are good too, but I reviewed them only once.

**Comment by zoli111** [comment]
Shall I make a new PR when they are ready too?

**Comment by tsujan** [comment]
I merge this one. Feel free to make PRs for changing anything in your translations if needed. Thanks!

**Pull request merged**
