### PR TITLE
If using Kvantum's shadows for menus, then move menu when shown so that

### PR DESCRIPTION
**Pull request by CDrummond**
it appears where the user would expect.

------------------------

OK, first pull request for Issue #128 This seems to fix things for me. The only issue is the overlap setting - if menus are to be moved, I just force this to be 0

### CODE REVIEW

**Comment by tsujan** [comment]
Oh, it seems that we didn't mean the same thing by "offset"! I meant *menubar menus*, which aren't aligned with their corresponding menubar-items, while you meant *submenus*.

Submenus were always *horizontally* aligned with their parent menus in the case of KvArc (submenu_overlap=0). I never cared about their vertical alignment with menu-items but since it's important to you, I'll fix it by using values that will work with all themes.

A question: Is there any horizontal overlap or gap between the original Kvantum submenus of KvArc (without this patch) and their parent menus under Gnome Shell? If there is, that's a Gnome problem and can't be fixed here.

**Comment by tsujan** [comment]
This is a KvArc submneu:

kvarc

There's neither a gap nor an overlap. Vertical alignment is another story (explained above and to be fixed).

**Comment by CDrummond** [comment]
My patch was to fix the horizontal (x axis) alignment. The offset part 
was because the 'move()' part caused an overlap, so I was trying to 
counter this.

Not sure what you mean by " I never cared about their vertical 
alignment with menu-items but since it's important to you, I'll fix it 
by using values that will work with all themes."

What I was trying to fix is... With composite enabled, so drawing 
Kvantum shadows, the menu was shifted to the right and down. So, the 
move() in the eventFilter() was to move the menu back to where it 
should be. This then caused sub-menus to sometimes overlap - I assume 
it was moving when it did not need to, hence the part with setting this 
to 0 (as it seemed to work around this).

The patch was for main menubar menus as well - this is where I first 
noticed the issue (as its quite obvious(

Does this not work for all styles?

**Comment by tsujan** [comment]
>  the menu was shifted to the right and down

Please take a look at the above screenshot! There's no shift to right for the submneu (yes, there's a vertical shift, which I'll fix). There's no gap between the left border of the submenu and the right border of the menu. there's no overlap either. That's what I called "horizontal alignment".

**Comment by tsujan** [comment]
> The patch was for main menubar menus as well

That doesn't work -- I'd experimented with it before; don't know why yet.

**Comment by CDrummond** [comment]
On Fri, 23 Jun, 2017 at 11:28 PM, tsujan <notifications@github.com> 
wrote:
>> The patch was for main menubar menus as well
>> 
> That doesn't work -- I'd experimented with it before; don't know why 
> yet.
> 

Works for me. Where does it not work? And in what way? All it does is 
move then menu left by the shadow amount.

**Comment by tsujan** [comment]
> Yeah - I know. But, as I said, the move() I added to the eventFilter caused sub menus to also move - creating an overlap. Which is what I then tried to counter-act.

OK. I'll fix the vertical shift later -- the values of this patch aren't compatible with all themes and submenu overlap shouldn't be nullified.

> Works for me. Where does it not work?

Yes it should work but doesn't here. I should check the menubar Qt source to find the cause. Maybe it depends on the window manager.

**Comment by CDrummond** [comment]
On Fri, 23 Jun, 2017 at 11:34 PM, tsujan <notifications@github.com> 
wrote:
>> Yeah - I know. But, as I said, the move() I added to the eventFilter 
>> caused sub menus to also move - creating an overlap. Which is what I 
>> then tried to counter-act.
>> 
> OK. I'll fix the vertical shift later -- the values of this patch 
> aren't compatible with all themes and submenu overlap shouldn't be 
> nullified.
> 

Fair enough - you know more than I. I did you the configured values, 
hence thinking it should work. I agree the overlap shoulnd't be 
nullified - but I thought that was better than having an overlap when 
it should not be. Plus I didnt fully understand the code below my 
nullifying :-)

>> Works for me. Where does it not work?
>> 
> Yes it should work but doesn't here. I should check the menubar Qt 
> source to find the cause. Maybe it depends on the window manager.
> 


Odd. As it was your fix for RTL submenus that got me thinking to do the 
move. I assume your RTL fix works with whichever window manager you are 
using.

In what way does it not work? Makes no change, or changes too much??

Craig.

**Comment by tsujan** [comment]
> In what way does it not work? Makes no change, or changes too much??

Doesn't change the menubar menu position at all.

Anyway, I'm motivated to attack the menubar issue again. I leave this open until it's fixed or it's proven that it can't be fixed ;) Thanks!

**Comment by CDrummond** [comment]
But it can be fixed - at least it is for me. See attached.


What app are you testing with? Please try VLC - just so that we are 
using the same.

**Comment by tsujan** [comment]
Very interesting! I set `w->move(w->x(), w->y()+20);` and opened VLC. Menubar menus don't move at all but the weird thing is that some VLC submenus move and some don't!! For example, "Open recent media" moves but View → playlist View Mode doesn't. I think this may be related to their parents *and* to the window manager.

BTW, no image is attached to your last comment but it isn't important; I know that menus are all moved in your case. Gnome shell magic?

**Comment by tsujan** [comment]
For the sake of certainty, I logged into KDE and tested there too: No difference at all. All submenus that were moved under Enlightenment were also moved under KDE and those that weren't moved under E weren't moved under KDE either.

Therefore, this cannot be related to window manager (Gnome shell is an exception). I'll look into it tomorrow.

**Comment by tsujan** [comment]
A interesting screenshot taken under KDE () with `w->move(w->x(), w->y()+20);`:

move

**Comment by CDrummond** [comment]
Ah! Didnt notice this conversation was on github! I was replyng via email! My screenshot:

vlc


Why are you testing with `move(w->(), w->y()+20)` - why no `move(w->x()-4, w->y()-3`, as this would be more appropriate.

**Comment by tsujan** [comment]
I'm sure this magic is made neither by Gnome shell nor by Qt but my sleepy mind -- my sleepy logic says, "that's impossible!" ;) Will be back with a fresh mind tomorrow.

**Comment by tsujan** [comment]
https://github.com/tsujan/Kvantum/commit/8eb2bcc89be70769da0ba2486dbe316d83409320 fixes the issue for all themes. It's a generalized form of your PR minus overlap nullification. The most important part was a simple condition for a menu to be a submenu.

BTW, I found out what happened here yesterday (my drowsiness) and why I had a false memory about a failure (a very different story).... Neither is important now.

Thanks for telling me about this issue and very sorry for my ignorance!

**Pull request closed without merging**
