### PR TITLE
Added dark red theme for KvRoughGlass

### PR DESCRIPTION
**Pull request by JoseskVolpe**
Hello, i've loved the RoughGlass theme and i've decided to make a dark, red version of it for my use.
I would like to share it and merge it into the repository to let other people use it too

Tell me if something more is needed

Screenshot_20220124_230912

### CODE REVIEW

**Comment by tsujan** [comment]
Thank you very much for your contribution!

Please make your own repository for sharing your themes with others — theme makers usually do so. You could consider the themes that come with Kvantum to be its author's (my)  contribution to Kvantum themes. Of course, they can also be used as a start point for creating other themes.

Also, https://store.kde.org has a Kvantum section for sharing Kvantum themes.

**Comment by JoseskVolpe** [comment]
¡Alright, i'll do so!
Also, one doubt. I've set author to "Tsu Jan, modified by Josesk Volpe", ¿is it fine?

**Comment by tsujan** [comment]
Yes, of course. *You* are the author. Themes can always be made based on other themes.

**Comment by JoseskVolpe** [comment]
Ok, alright :3

**Comment by JoseskVolpe** [comment]
Published to: https://www.pling.com/p/1690514/

**Pull request closed without merging**
