### PR TITLE
Don't force sizegrip in KvCommunitheme

### PR DESCRIPTION
**Pull request by CDrummond**
Reduce headerview borders
Bold for default button - may need changing when communitheme settles on
what this should be

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks for your attention! I'll close it when it's done in the next commit -- which will be a big one, including 2 new features too.

**Comment by tsujan** [comment]
Changed view border and header (not pushed yet; maybe tomorrow, after testing the changes to Kvantum itself):

view

**Comment by CDrummond** [comment]
Looks great!

**Comment by tsujan** [comment]
BTW, shouldn't group-boxes have similar borders with their texts inside their truncated top borders?

**Comment by CDrummond** [comment]
On Mon, 2 Apr, 2018 at 8:03 PM, tsujan <notifications@github.com> wrote:
> BTW, shouldn't group-boxes have similar borders with their texts 
> inside their truncated top borders?
> 
Technically speaking, yes. But, most Gtk apps don't draw the frame. 
Whereas most KDE/Qt apps just the styles default. Therefore, the 
default of the style should be bold text, and no frame - as per 
KvAmbiance.

Craig.
>

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/0b4e270371e811cab7238a5634b9638bcebc697c

**Comment by CDrummond** [comment]
Thanks for the update, looking GREAT!

**Pull request closed without merging**
