### PR TITLE
Expand x11drag option to allow finer grained control. Allows setting …

### PR DESCRIPTION
**Pull request by CDrummond**
…to drag from all menubar only, menubar and primary toolbar, all areas, or no dragging.

### CODE REVIEW

**Comment by tsujan** [comment]
Thank you for the time you put into implementing this nice feature! I merge it now. Tomorrow I may make some minor changes (rearranging, resizing, doc, etc.).

The next GitHub release (0.10.2) will all be about your work :)

**Comment by CDrummond** [comment]
On 19/08/16 22:01, tsujan wrote:
>
> Thank you for the time you put into implementing this nice feature!
>
Well the work was already done in QtCurve's version of windowmanager - 
and I also use this in some of my apps, to have a more Gtk like 
appearance under Unity.

> I merge it now. Tomorrow I may make some minor changes (rearranging, 
> resizing, doc, etc.).
>
> The next GitHub release (0.10.2) will all be about your work :)
>

Before that - I think it'd be nice to resolve the shadow issue. Even if 
it is having a list of desktop on which a theme will not use compositing.

I really like the Arc set of themes, so would like to create as close a 
match as possible with Kvantum, Then my Qt apps would not need to use 
QGtkStyle, or the various hacks I have added :-)

Craig.

**Comment by tsujan** [comment]
> Before that - I think it'd be nice to resolve the shadow issue.

Composited Kvantum menus are OK with Compton, Compiz+Emerald, Kwin and Enlightenment. That shadow issue is *Unity's* issue because, apparently, it doesn't have a setting for disabling argb menu shadows. Anyway, the user could easily disable compositing with KM; so, I don't think this is a serious issue.

> I really like the Arc set of themes, so would like to create as close a match as possible with Kvantum,

IMO, that should be possible. I haven't seen Arc yet but will try it when I find some free time and, if it's elegant, I may make and add "KvArc" to Kvantum ;)

**Comment by CDrummond** [comment]
On 19/08/16 22:58, tsujan wrote:
>
>     Before that - I think it'd be nice to resolve the shadow issue.
>
> Composited Kvantum menus are OK with Compton, Compiz+Emerald, Kwin and 
> Enlightenment. That shadow issue is /Unity's/ issue because, 
> apparently, it doesn't have a setting for disabling argb menu shadows. 
> Anyway, the user could easily disable compositing with KM; so, I don't 
> think this is a serious issue.
>

Fair enough - but I use Unity :-) If Composite is disabled in the theme, 
I take it there's no menu shadows under KDE? This is what I hate about 
this. It used to be that the WM provided the shadows, until Oxygen 
wanted rounded shadows. Now all styles need to provide them. That's bad. 
It should be that the theme can provide them if it wishes, but the WM 
should have a fallback.

>     I really like the Arc set of themes, so would like to create as
>     close a match as possible with Kvantum,
>
> IMO, that should be possible. I haven't seen Arc yet but will try it 
> when I find some free time and, if it's elegant, I may make and add 
> "KvArc" to Kvantum ;)
>

https://github.com/horst3180/arc-theme

There's 3 variants:

Arc
Arc-Dark
Arc-Darker - which is a blend of the above 2. This is the one that I 
like - it has dark toolbars, but lighter elsewhere. Someone has tried a 
port of Arc using Kvantum - https://github.com/varlesh/Arc-KDE But this 
has *many* issues:

     1. No icons in toolbar buttons
     2. Icons on push buttons
     3. Need white text for pressed pushbuttons
     4. Toggle button should be blue when selected
     5. Toolbutton should be blue when pressed
     6. Need horizontal spin
     7. Menu highlight should be blue, with white text
     8. Margins too small
     9. Set Min size for push buttons
    10. Tabs should have frame on mouse over
    11. Lineedits, etc, should have white background
    12. Lineedits too thin
    13. Group boxes should have bold title and no frame


Does Kvantum support a GroupBox with bold title, and no frame? I'm 
pretty sure it does, just need to find the setting...

Craig.

**Comment by tsujan** [comment]
> If Composite is disabled in the theme, I take it there's no menu shadows under KDE?

When the user is under Unity, he/she just checks a check box in Kvantum Manager and Kvantum menus will use Unity's shadow. When he is under KDE, he unchecks the same box and Kvantum menus will use own shadows (provided that the theme has menu shadow -- all themes that I've included in Kvantum have it).

However, after you told me about Unity and I tested it in VirtualBox, an idea came to me: adding an option to Kvantum Manager for having *shadowless composited menus*. That's possible and I'll do it before the next release.

> Does Kvantum support a GroupBox with bold title, and no frame?

Any frame can be omitted but, although Kvantum supports bold text in many places, it doesn't do so in the case of Groupbox labels. But I'll think about it.

> https://github.com/horst3180/arc-theme

Thanks for the link and the list of issues. It may take some time but I'll make an Arc theme.

All in all, Kvantum has grown mostly because its users (including me) wanted to make new themes that required more and more features. For example, I wanted to make themes with completely rounded corners and, for months, though it was impossible with an SVG engine. However, one day, the idea of `frame expansion` came to my mind, as if out of nowhere ;) The same is true about the features you’ve suggested, added or want :)

**Comment by CDrummond** [comment]
On 19/08/16 23:41, tsujan wrote:
>
>     If Composite is disabled in the theme, I take it there's no menu
>     shadows under KDE?
>
> When the user is under Unity, he/she just checks a check box in 
> Kvantum Manager and Kvantum menus will use Unity's shadow. When he is 
> under KDE, he unchecks the same box and Kvantum menus will use own 
> shadows (provided that the theme has menu shadow -- all themes that 
> I've included in Kvantum have it).
>

Your choice - but I think she work as best as possible without user 
interaction. Unity is a highly used DE - and the menu shadows give a 
really bad first impression. I know its not 100% Kvantum's fault - but a 
workaround is easy enough.
>
> However, after you told me about Unity and I tested it in VirtualBox, 
> an idea came to me: adding an option to Kvantum Manager for having 
> /shadowless composited menus/. That's possible and I'll do it before 
> the next release.
>
Shadow less menus? Yuck - that would look BAD.

>     Does Kvantum support a GroupBox with bold title, and no frame?
>
> Any frame can be omitted but, although Kvantum supports bold text in 
> many places, it doesn't do so in the case of Groupbox labels. But I'll 
> think about it.
>

Ah - should be easy enough todo. I can add it to my list - QtCurve had 
this feature.

**Comment by tsujan** [comment]
> Shadow less menus? Yuck - that would look BAD.

I agree. As I said, in all of my themes menus have shadow. The checkbox in question will remove those shadows optionally -- without disabling compositing -- for Unity to force its shadow on Qt menus consistently.

> Unity is a highly used DE

Because of the GTK patches it needs, Unity can't be used *safely* on distros other than Ubuntu and its derivatives; hence, my lack of knowledge about it (I was a Debian user for about a decade and migrated to Manjaro last month).

**Comment by tsujan** [comment]
After some tests, I found that Unity's problem with argb Qt menus is *random*. Therefore, it's either a Unity bug or (more probably) a bug in Qt. In the folowing screenshot, I caught an example of *correct* shadow with the default Kvantum theme and with compositing enabled:

menushadow

So, there's no need to a "shadowlessness" checkbox after all.

**Comment by CDrummond** [comment]
On 20/08/16 18:28, tsujan wrote:
>
> After some tests, I found that Unity's problem with argb Qt menus is 
> /random/. Therefore, it's either a Unity bug or (more probably) a bug 
> in Qt. In the folowing screensho
>

Is this in VBox? I'm *always* getting the issue. Its like compiz draws 
it shadows on top of Kvantum's. Perhaps there is soke sort of hint that 
can be added to state that he WM should not draw shadows?

Craig.

**Comment by tsujan** [comment]
> Is this in VBox?

Yes! What I know is that Qt5 doesn't announce its menus as menus but as normal windows (https://bugreports.qt.io/browse/QTBUG-47043). So, if the problem only happens with Qt5 apps, it should be a Qt5 bug; otherwise, it's a Unity bug.

**Comment by tsujan** [comment]
Oh, I forgot something: I've included a workaround for QTBUG-47043 in Kvantum. So it can't be the cause.

**Comment by CDrummond** [comment]
Hmmm... Just tried hacking that bit of code to set various values, 
nothing worked!

Looking at your screenshot, there is a lighter 'shadow'/section to the 
left of the menu. Is this a Kvantum shadow bug, or Unity?

Craig.

**Comment by tsujan** [comment]
I suspected Qt5 but after installing VLC on Ubuntu, I saw the same randomness. So, most probably, this is about a Unity bug.

> Looking at your screenshot, there is a lighter 'shadow'/section to the left of the menu.

Oh, that's just because of converting PNG to JPG.

Kvantum's menu shadows are really simple: they're just parts of the SVG menu elements. That's because Kvantum is supposed to work everywhere and with any window manager or compositor.

**Comment by tsujan** [comment]
About Arc:

I checked Arc-KDE and think its author didn't want to copy Arc. All items on your list (probably, except for tab frame on mousover) can be made right. I'll make a theme similar to Arc as soon as I have free time.

**Comment by CDrummond** [comment]
On Sun, 21 Aug, 2016 at 3:37 PM, tsujan <notifications@github.com> 
wrote:
> About Arc:
> 
> I checked Arc-KDE and think its author didn't want to copy Arc.
> 

You sure? Looks like it should be similar  - if the issues were fixed.
> All items on your list (probably, except for tab frame on mousover) 
> can be made right.
> 
And why can't this be done? I guess because kvantum lacks support? If 
so, should be easy enough to add - I'll look into it.
> I'll make a theme similar to Arc as soon as I have free time.
> 
Was thinking about 'Arc-Darker' - this has a dark toolbar, with 
white-ish monochrome icons. I assume this would be very hard for 
kvantum todo - as it would not know that the icons are monochrome and 
need recolouring? If so, then I guess its just Arc and Arc-Dark that 
can be mimicked.



My aim with all this, is that same as it was with QtCurve - to have as 
consistent a desktop as possible. Hence wanting to somehow make Qt 
matching themes for Gtk themes. Ideally I'd love it if kvantum became 
the de-facto Qt theme engine. Then theme authors would create a Gtk2, 
Gtk3, and Kvantum theme.

Craig.

**Comment by tsujan** [comment]
> And why can't this be done?

I didn't said it can't (I intentionally used the word "probably"). Kvantum has already a complex setting for tabs. I should make the theme first.

> My aim with all this, is that same as it was with QtCurve - to have as consistent a desktop as possible.

It is possible with Kvantum too. Take a look at KvGnome and KvGnomeDark, for example. As another example, Kvantum's default theme is very similat to https://github.com/tsujan/E17gtk.git

I'm working on `KvArc` now. It may take some time...

**Comment by CDrummond** [comment]
On 21/08/16 17:11, tsujan wrote:
>
>     And why can't this be done?
>
> I didn't said it can't (I intentionally used the word "probably"). 
> Kvantum has already a complex setting for tabs. I should make the 
> theme first.
>

Ah, sorry - didn't mean to offend. Was merely asking if the 
functionality had been implemented or not. I don't mind looking in to 
adding this - its quite common for themes to want mouse-over for tabs.
>
>     My aim with all this, is that same as it was with QtCurve - to
>     have as consistent a desktop as possible.
>
> It is possible with Kvantum too. Take a look at KvGnome and 
> KvGnomeDark, for example. As another example, Kvantum's default theme 
> is very similat to https://github.com/tsujan/E17gtk.git
>
> I'm working on |KvArc| now. It may take some time...
>

Cool! I look forward to it. I was going to try to fix the Arc issues 
myself - but if you want to do this, fine with me :-) you'll be *much* 
faster than me any way :-)

Craig.

**Comment by tsujan** [comment]
> Ah, sorry - didn't mean to offend

No offence taken at all :) Making a theme for Kvantum may be a long process -- one can't know what will happen in the case of complex widgets.

**Comment by tsujan** [comment]
Tab frame on mousover trurned out to be quite possible :) I'll tell you when the theme is finished.

**Comment by CDrummond** [comment]
On 21/08/16 17:46, tsujan wrote:
>
> Tab frame on mousover trurned out to be quite possible :) I'll tell 
> you when the theme is finished.
>

He he :-) Knew it was technically possible - as QtCurve does this....

**Comment by tsujan** [comment]
Almost ready -- except for some details. Your app with it:

kvarc

**Comment by tsujan** [comment]
I added `KvArc` to Kvantum. It needs the latest git Kvantum because of some fixes and changes. It’s not an *exact* clone of Arc but has its look and feel. I’d be grateful if you test it and let me know your opinion.

I kept the original colors (from the link you gave me) as far as possible.

Horizontal spin buttons *could* be made wider in the code (in fact, a key could be added for that) but I didn’t do so intentionally: Many Qt app developers don’t consider the possibility of horizontal spinboxes and set a small fixed width for them, so that in their case, the spin text would be partially hidden if wide spin buttons were used.  Wrong fixed widths/heights have been a nightmare for me in developing Kvantum ;) I had to add many workarounds just for them.

I kept a partial frame for groupboxes because they would look weird without it.

**Comment by CDrummond** [comment]
On Mon, 22 Aug, 2016 at 2:19 PM, tsujan <notifications@github.com> 
wrote:
> I added KvArc to Kvantum. It needs the latest git Kvantum because of 
> some fixes and changes. It’s not an exact clone of Arc but has its 
> look and feel. I’d be grateful if you test it and let me know your 
> opinion.
> 

Looks great! Issues so far:

1. Mono icons should be white when toolbar buttons pressed. This is 
(obviously) dependant upon the icon engine. The KDE one, and the one in 
Cantata (from master) handles this by passing 'selected' as the icon 
state when getting the pixmap.
2. View frames should be completely square - and lighter, border is too 
dark
3. In list views, etc. checkboxes should be inverted for selected items 
- as per menus.
4. Focus rect should be a light dotted rectangle
5. Don't shift text in buttons
6. Default button should not have triangle or bold text. But Arc does 
not seem to mark this. I guess using the blue background might be nicer?
7. Need to set a minimum button size - at least for dialog buttons. 
"OK" is way too small
8. Dialog margins and spacing should be increased
9. Spin buttons *must* be wider - way too 'thin'
10. Spin button should use the same background as the entry - and the 
focus highlight should go around these. Also, remove the line between 
the '-' button and the entry
11. Cantata explicitly removes icons from menus. These are not draw in 
Kvantum, but space is still reserved. If I disable these in the 
kvconfig, then looks ok.
12. Toolbar buttons should be flat if not selected, pressed, or 
mouse-over - i.e. as per 'auto raise'
13. Window drag should be on menubar and toolbar only
14. Slider thumb (the circle) should be blue when pressed
15. Progressbar text should not be bold
16. Treeviews should use arrows for expanders - not +/-
> I kept the original colors (from the link you gave me) as far as 
> possible.
> 
> Horizontal spin buttons could be made wider in the code (in fact, a 
> key could be added for that) but I didn’t do so intentionally: Many 
> Qt app developers don’t consider the possibility of horizontal 
> spinboxes and set a small fixed width for them, so that in their 
> case, the spin text would be partially hidden if wide spin buttons
> 

You need to account for this is sizeForContents. For Cantata, if using 
QGtkStyle, I added a proxt style to draw these style spin buttons. I 
had issues with Qt5, but managed to fix these. See sizeForContents in 
https://github.com/CDrummond/cantata/blob/master/support/touchproxystyle.cpp
> I kept a partial frame for groupboxes because they would look weird 
> without it.
> 

Must admit I do like the look. However, to match it should not have the 
frame. Setting 'groupbox_top_label' to true and 'frame' (in GroupBox 
section) to false fixes this. But then the contents of the group box 
need to be indented - again this is probable because the margins are 
too small.


Craig.

**Comment by CDrummond** [comment]
On Mon, 22 Aug, 2016 at 9:09 PM, Craig Drummond 
<craig.p.drummond@gmail.com> wrote:
> 
> 
> On Mon, 22 Aug, 2016 at 2:19 PM, tsujan <notifications@github.com> 
> wrote:
>> I added KvArc to Kvantum. It needs the latest git Kvantum because of 
>> some fixes and changes. It’s not an exact clone of Arc but has its 
>> look and feel. I’d be grateful if you test it and let me know your 
>> opinion.
>> 
> 
> Looks great! Issues so far:
> 
> 1. Mono icons should be white when toolbar buttons pressed. This is 
> (obviously) dependant upon the icon engine. The KDE one, and the one 
> in Cantata (from master) handles this by passing 'selected' as the 
> icon state when getting the pixmap.
> 2. View frames should be completely square - and lighter, border is 
> too dark
> 3. In list views, etc. checkboxes should be inverted for selected 
> items - as per menus.
> 4. Focus rect should be a light dotted rectangle
> 5. Don't shift text in buttons
> 6. Default button should not have triangle or bold text. But Arc does 
> not seem to mark this. I guess using the blue background might be 
> nicer?
> 7. Need to set a minimum button size - at least for dialog buttons. 
> "OK" is way too small
> 8. Dialog margins and spacing should be increased
> 9. Spin buttons *must* be wider - way too 'thin'
> 10. Spin button should use the same background as the entry - and the 
> focus highlight should go around these. Also, remove the line between 
> the '-' button and the entry
> 11. Cantata explicitly removes icons from menus. These are not draw 
> in Kvantum, but space is still reserved. If I disable these in the 
> kvconfig, then looks ok.
> 12. Toolbar buttons should be flat if not selected, pressed, or 
> mouse-over - i.e. as per 'auto raise'
> 13. Window drag should be on menubar and toolbar only
> 14. Slider thumb (the circle) should be blue when pressed
> 15. Progressbar text should not be bold
> 16. Treeviews should use arrows for expanders - not +/-

Oh, and I forgot to add that I'm more than happy to look into the 
above. You've create a fantastic starting ground :-)

**Comment by tsujan** [comment]
Thank you very much for testing the theme and taking time to tell me about your ideas!

I'll change the theme according to your following suggestions:

● View frames should be completely square - and lighter, border is too dark
● In list views, etc. checkboxes should be inverted for selected items - as per menus.
● Don't shift text in buttons
● Slider thumb (the circle) should be blue when pressed
● Progressbar text should not be bold
● Treeviews should use arrows for expanders - not +/-

However:

> In list views, etc. checkboxes should be inverted for selected items - as per menus.

That may be possible with some change in the code. I'll look into it.

> Focus rect should be a light dotted rectangle

I haven't added focus rect to any of my themes because, IMO, it's ugly and not so useful. I always hated it when I used GTK ;) Kvantum supports focus rects but not dotted ones (yet).

> Need to set a minimum button size - at least for dialog buttons

The size of buttons can be increased by increasing text margin size. How many pixels bigger do you want them to be?

> Dialog margins and spacing should be increased

If you mean the layout spacing, Kvantum has a key for it (in Kvantum Manager).

> Spin button should use the same background as the entry

I copied Arc exactly -- in Arc they don't.

> Also, remove the line between the '-' button and the entry

I modified the code for that line/separtor to be able to mimic Arc and some other GTK themes ;)

> Toolbar buttons should be flat if not selected, pressed, or mouse-over

THEY ARE ;) aren't they?

> Spin buttons *must* be wider - way too 'thin'... You need to account for this is sizeForContents

I'm afraid that's not possible. If you search for "IndicatorSpinBox" in `Kvantum.cpp`, you'll see in how many places I had to consider exceptions. As I said above, those exceptions are caused by bad GUI design. We can't change *fixed widget sizes*. The situation is worse with QML...

There are two other things that I forgot to say before:

(1) IMO, GTK and Qt can't copy each other's themes *exactly* unless the themes in question are simple enough. We can just hope for a fair similarity. Among Kvantum's extra themes you could find themes that can't have an *exact* GTK copy, and there are GTK themes that can't be copied *exactly* by QStyle.

(2) I vaguely remember you told about a light GTK theme with dark toolbar/menubar. Kvantum supports that :)

**Comment by CDrummond** [comment]
> However:
>
>     In list views, etc. checkboxes should be inverted for selected
>     items - as per menus.
>
> That may be possible with some change in the code. I'll look into it.
>
>     Focus rect should be a light dotted rectangle
>
> I haven't added focus rect to any of my themes because, IMO, it's ugly 
> and not so useful. I always hated it when I used GTK ;) Kvantum 
> supports focus rects but not dotted ones (yet).
>

Can't the rect just be a SVG?
>
>     Need to set a minimum button size - at least for dialog buttons
>
> The size of buttons can be increased by increasing text margin size. 
> How many pixels bigger do you want them to be?
>
Its not just the margins. For QDialogButton box buttons, there should be 
a minimum size. QtCurve used to set a minimum size for all pushbuttons - 
if the text was not "..." (this was from Kontact). As I said, the OK 
buttons in dialogs is too thin. Just adding margins will increase the 
size of all buttons  - and OK will still be too small relative to the 
others.

>     Dialog margins and spacing should be increased
>
> If you mean the layout spacing, Kvantum has a key for it (in Kvantum 
> Manager).
>
Yes - but this should be in the style. Is it not?
>
>     Spin button should use the same background as the entry
>
> I copied Arc exactly -- in Arc they don't.
>
>     Also, remove the line between the '-' button and the entry
>
> I modified the code for that line/separtor to be able to mimic Arc and 
> some other GTK themes ;)
>

You are right - sorry should have checked! I was comparing against my 
memory of other themes! Sorry :-(
>
>     Toolbar buttons should be flat if not selected, pressed, or mouse-over
>
> THEY ARE ;) aren't they?
>

They are. It's in KvantumPreview that they are raised. On the subject of 
KvantumPreview - should this also not be set to always use kvantum? As 
per KvantumManager? Perhaps even allow multiple instances with different 
themes?
>
>     Spin buttons /must/ be wider - way too 'thin'... You need to
>     account for this is sizeForContents
>
> I'm afraid that's not possible. If you search for "IndicatorSpinBox" 
> in |Kvantum.cpp|, you'll see in how many places I had to consider 
> exceptions. As I said above, those exceptions are caused by bad GUI 
> design. We can't change /fixed widget sizes/. The situation is worse 
> with QML...
>

OK. I'll have a play - but you know more about this than me.
>
> There are two other things that I forgot to say before:
>
> (1) IMO, GTK and Qt can't copy each other's themes /exactly/ unless 
> the themes in question are simple enough. We can just hope for a fair 
> similarity. Among Kvantum's extra themes you could find themes that 
> can't have an /exact/ GTK copy, and there are GTK themes that can't be 
> copied /exactly/ by QStyle.
>

I agree. But, it'd be nice to make then look as similar as possible :-)  
As I said, I'm happy to look into any of the issues I raised - don't 
want you to think that I'm trying to give you lots of work :-)
>
> (2) I vaguely remember you told about a light GTK theme with dark 
> toolbar/menubar. Kvantum supports that :)
>

Yeah - Ark-Darker does this. The issue, I think, that a Qt style would 
see is in the colour of monochrome icons on the toolbar. These would 
need to be white (or rather, the toolbar text colour) and dark elsewhere.


Craig.

**Comment by tsujan** [comment]
> Can't the rect just be a SVG?

In Kvantum, everything -- including focus rect -- is drawn by using SVG objects. Dotted focus rect would be like menu tear-off, which is already dotted.

> there should be a minimum size

Oh, Kvantum already has it. You didn't tell about your preferred minimum size in pixels.

> Yes - but this should be in the style. Is it not?

You mean in the app style? Yes, but there are also global sapcings (PM_LayoutHorizontalSpacing and PM_LayoutVerticalSpacing), which Kvantum controls.

> They are. It's in KvantumPreview that they are raised...

Ah, I always forget that you're on Unity! You're right; I should force Kvantum on kvantumpreview too. Thanks for reminding me!

> OK. I'll have a play - but you know more about this than me.

In `Kvantum.cpp`, we have SPIN_BUTTON_WIDTH. Its value can be changed from 16 to any size and a key can be used instead of it. Then, all "good" spin buttons will be wider, as you (and I) prefer. However, if `SPIN_BUTTON_WIDTH > 16`, all calculations about exceptional cases will be wrong. If I free spin buttons from this limitation and if my users say, for example, "why do Pencil's (or VLC's) spin texts go behind spin buttons?" I'll have to answer "because their developers did it wrong."

Now, the (false) problem is that such apps look normal with Fusion, Breeze and even QtCurve because these engines presuppose 16-px vertical spin buttons.

I wanted to remove those limitations several times but wasn't sure. What do you think? Should I remove them?

>  don't want you to think that I'm trying to give you lots of work :-)

I'd be glad if you do ;) Such details may not be limited to a specific theme.

> Yeah - Ark-Darker does this. The issue, I think, that a Qt style would see is in the colour of monochrome icons on the toolbar...

Unfortunately, Qt doesn't have this feature. For example, `KvFlatLight` is a dark-and-light theme that many Kvantum users like. With suitable colored icons, everything is OK. But.... see what happens with Cantata:

kvflatlight

I couldn't find an option in Cantata for using system icons instead of own icons.

**Comment by tsujan** [comment]
Reached a compromise on horizontal spin buttons :-) I added a key to Kvantum Manager → Configure Active Theme → Sizes.

(1) "Good" spin boxes *can* have wide buttons, up to 32px:

good

(2) "Ugly" spinboxes (rare and not ugly at all) are automatically detected and 16-px buttons are forced on them:

ugly

(3) "Bad" spinboxes (*very* rare and ugly) have 8-px buttons automatically.

(4) QML spin button are always verical, as before.

I modified the theme according to your suggestions and also added tree branch line (to the theme and Kvantum). But I didn't remove the default button triangle -- I think it's an elegant way of marking default buttons.

"OK" button is OK here. Please give me a minimum width/height if you think it's too small!

Thanks for this long discussion!

**Comment by CDrummond** [comment]
On Tue, 23 Aug, 2016 at 5:04 PM, tsujan <notifications@github.com> 
wrote:
> Reached a compromise on horizontal spin buttons :-) I added a key to 
> Kvantum Manager → Configure Active Theme → Sizes.
> 
They look *fantastic* now - well done! :-)
> 
> (3) "Bad" spinboxes (very rare and ugly) have 8-px buttons 
> automatically.
> 

In this case would they not be better vertical?

> I modified the theme according to your suggestions and also added 
> tree branch line (to the theme and Kvantum).
> 

Hmmm... Don't like the line - adds too much visual clutter

> But I didn't remove the default button triangle -- I think it's an 
> elegant way of marking default buttons.
> 

I like it too :-) Just noticed Arc Gtk does *not* mark the default 
button - bit horrible that! It should be marked somehow.

> "OK" button is OK here. Please give me a minimum width/height if you 
> think it's too small!
> 

Attached is a screenshot of QtCreator's config dialog. You can see that 
the Kvatum OK button is very thin  - whereas in QGtkStyle (and QFusion, 
etc) the buttons are more evenly sized/

> Thanks for this long discussion!
> 


Hope its not too long! :-)

I've fixed the issues with Cantata - please try git/master. I've 
submitted a pull request so that in menus the monoicons are coloured 
the same as the text. This works for Cantata - and should work for all 
KDE apps using the breeze icon theme. Now, toolbuttons and push buttons 
have a similar issue. With Arc the toggled/pressed buttons have a blue 
background, white text, but still dark icon. Now I can think of 3 ways 
to fix this:

1. Have a general config item - use_selected_icons
2. Have this config item be per button type
3. In the code, check if the current button text colour == highlight 
text colour, and button is checked/pressed, and then use QIcon::Selected

I'm leaning towards 1 - as it'd be easier :-) But thought I'd check 
with you first.

Craig.

**Comment by tsujan** [comment]
Glad to know you like the spin buttons now.

>> (3) "Bad" spinboxes (very rare and ugly) have 8-px buttons automatically.

> In this case would they not be better vertical?

Maybe! I may change it.

> Hmmm... Don't like the line - adds too much visual clutter

Me neither but Arc has it. And it can be disabled by KM.

> Attached is a screenshot of QtCreator's config dialog..

You forgot the image. Here, Kvantum buttons look OK in QtCreator's config dialog, even without icons:

buttons

>> Thanks for this long discussion!

> Hope its not too long! :-)

LOL! I didn't mean that :) It was very fruitful to me.

> I've fixed the issues with Cantata - please try git/master

Thanks! I'll try your commits tomorrow.

**Comment by CDrummond** [comment]
On 23/08/16 20:57, tsujan wrote:
> Hmmm... Don't like the line - adds too much visual clutter
>
> Me neither but Arc has it. And it can be disabled by KM.
>

Ah! I've been looking at it in thunderbird - which is using Gtk2. Your 
right it does have the lines - but they are lighter. Also, yours have 
dark dots where the horizontal an vertical meet.
>
>     Attached is a screenshot of QtCreator's config dialog..
>
> You forgot the image. Here, Kvantum buttons look OK in QtCreator's 
> config dialog, even without icons:
>

Ah - replied using Geary - think it must have messed it up. Even in your 
screenshot you can see that the Fusion buttons are nice and wide - 
whereas the OK is too narrow in Kvantum.
Craig.

**Comment by tsujan** [comment]
>  Even in your screenshot you can see that the Fusion buttons are nice and wide - whereas the OK is too narrow in Kvantum.

So, you mean their width; don't you? `text.margin.left`

**Comment by tsujan** [comment]
Sorry I hit ENTER accidentally... `text.margin.left` and `text.margin.righ` control the width.

**Comment by CDrummond** [comment]
> So, you mean their width; don't you? |text.margin.left|
>

|Yes - but its not just the margin - its a *minimum size* e.g.

..Apply..  ...OK...  .Discard.
|
|Each of these is roughly the same size - but the margins are different. 
Yes there should be a min margin - don't want the text against the border.

But what Kvanum has is

.Apply .OK. .Discard.

Now 'OK' is too narrow.

Craig.
|

**Comment by tsujan** [comment]
> Apply .OK. .Discard. Now 'OK' is too narrow.

Now I understand! The key `size.minwidth` is for that but it may not be enough. I should make it depend on font/icon size. Will do so soon.

**Comment by tsujan** [comment]
I implemented what you were trying to tell me but I didn't get ;) i.e. minimum width plus centered text+icon. I'm sure you meant this:

centered

I'll make a commit after some tests (maybe tomorrow). Thanks for your persistence :)

**Comment by CDrummond** [comment]
On 23/08/16 23:06, tsujan wrote:
>
> I implemented what you were trying to tell me but I didn't get ;) i.e. 
> minimum width plus centered text+icon. I'm sure you meant 
> this:centered 
> <https://cloud.githubusercontent.com/assets/981076/17911538/3cc2dae0-69a3-11e6-9f18-6634191bddf3.png> 
>
>
Looks good!

> I'll make a commit after some tests (maybe tomorrow). Thanks for your 
> persistence :)
>

Thanks for your work! Must admit I love the KvArc group boxes :-)


Craig.

**Pull request merged**
