### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
- Changed the distro specific prerequisites to make them more uniform.
- Changed order of distro specific prerequisites to make it more appealing.
- Added a category for Leap and Tumbleweed because they have a different installation procedure.
- Alphabeticalised Leap and Tumbleweed.
- Added little note for Gentoo users.
- Added hyperlink for Theme-Making.

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks! I'll include most of these changes in a future PR; I don't want to change some things (like dependency grouping). Until then, I'll keep this open.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/9b73213e788e319b903fa6be96dce49bcb273c61

Your expertise in markdown is really appreciated; you made those files usable online. I mentioned that in README.

**Comment by TheEvilSkeleton** [comment]
This means a lot to me. I'm glad you're appreciating my work, just like I appreciate your project. Thi

**Comment by tsujan** [comment]
Actually, it's more than an appreciation: I learned a lot about markdown from you -- previously, I only knew its syntax (had to deal with it in the C++ code of one of my apps) but now, I know more about its practical usage :) I might change my other markdown files accordingly.

**Comment by TheEvilSkeleton** [comment]
Seriously? This is making me so happy right now, I have learned markdowns by just forking and looking at other people's READMEs. Here are some you should look at if you want to learn more from https://github.com/Nanolx/NanoDroid and https://github.com/pcqpcq/open-source-android-apps

**Comment by tsujan** [comment]
> I have learned markdowns by just forking and looking at other people's READMEs

The practical way is always the best way.

> Here are some you should look at

I will. Thanks.

**Comment by TheEvilSkeleton** [comment]
I forgot to mention that I got its layout from the Arch and Gentoo wikis.

**Pull request closed without merging**
