### PR TITLE
If run under GNOME, Unity, or Elementary (Pantheon), then set font fr…

### PR DESCRIPTION
**Pull request by CDrummond**
…om DConf/GSettings, and disable button and menu icons.

### CODE REVIEW

**Comment by tsujan** [comment]
This is nice. Two questions:

(1) Can iconlessness of buttons and menus be taken from gtk settings instead of being set to `true` always?

(2) Does `SH_DialogButtonBox_ButtonsHaveIcons` have eny effect? When `iconless_pushbutton` is set to true, all push-button are iconless, including dialog buttons.

**Comment by CDrummond** [comment]
On 26 Aug 2016 11:38, "tsujan" <notifications@github.com> wrote:
>
> This is nice. Two questions:
>
> (1) Can iconlessness of buttons and menus be taken from gtk settings
instead of being set to true always?

Could do, and would be more "correct". There are settings for these. But I
wanted to avoid repeated calls to dconf. Also, do any gtk desktops use
icons in menus and buttons??

> (2) Does SH_DialogButtonBox_ButtonsHaveIcons have eny effect? When
iconless_pushbutton is set to true, all push-button are iconless, including
dialog buttons

Probably safe to remove, I just added for completeness.

**Comment by tsujan** [comment]
> Also, do any gtk desktops use icons in menus and buttons??

I've been far from gtk for a long time. I mean if the user can change that setting, wouldn't it be better to read it? But If that requires repeated calls to dconf and has a negative impact on performence, the current solution is better.

**Comment by CDrummond** [comment]
On 26 Aug 2016 11:51, "tsujan" <notifications@github.com> wrote:
>>
>> Also, do any gtk desktops use icons in menus and buttons??
>
> I've been far from gtk for a long time. I mean if the user can change
that setting, wouldn't it be better to read it? But If that requires
repeated calls to dconf and has a negative impact on performence, the
current solution is better.

This method uses the command line tools, to save linking against dconf,
etc. Can't see how to get multiple values with these without multiple
calls. Not sure about the performance impact, as I've never really measured
it.

Still, for the 3 desktops mentioned, these do not use the icons. A user
would need to use dconf to change this.

**Comment by tsujan** [comment]
> A user would need to use dconf to change this.

That's what I meant: if, for example, the user makes gtk menus have icon, Qt menus will have icon too. But never mind, for now! I'll merge this PR after testing it under Unity. If you find an easy and acceptable way to read those settings, please make another commit!

**Comment by CDrummond** [comment]
It is easy to read the settings - you just need to call dconf/gsettings again for each. I just don't think its worth the hassle...

**Comment by tsujan** [comment]
> I just don't think its worth the hassle...

OK! I agree.

**Comment by tsujan** [comment]
Working with apps like Lyx will be really difficult if we enforce iconless menus:

menus

IMO, we shouldn't follow Gnome3 devs -- they have a bad habit of not thinking about the consequences of what they do ;)

**Comment by CDrummond** [comment]
This **only** affects users running under GNOME environments - and these do not have icons in menus. Each app should blend in with the DE it is running under. This is what Cantata attempts to do, and is what this patch does.

**Comment by tsujan** [comment]
> Each app should blend in with the DE it is running under.

I agree, *as far as there's no harm to usability*. Usability is what Gnome3 devs don't care about (I was a Gnome user 5 years ago). I use Lyx to write mathematical texts on a regular basis and would curse the author of Kvantum for those enforced iconless menus ;) I can't add Lyx to the list of exceptions in Kvantum because, first, that list is already bloated and, second, Lyx isn't alone in this.

> To be honest, I see nothing wrong in the right hand screenshot.

Icons are for finding items as fast as possible and users unconsciously take advantage of them. With complex tasks, there's no time to waste for finding items.

**Comment by CDrummond** [comment]
LibreOffice has much larger menus, and no icos - I have no difficulty using it. macOS does not have menu icons either.

I was a KDE user sine KDE 1.1.2 until KDE4.6(?), but I prefer the Unity way. 

I guess the compromise is to read the dconf setting. If this disables menu icons, then there should be none.

**Comment by tsujan** [comment]
> I guess the compromise is to read the dconf setting

That would be the best solution if it weren't for the dconf hassle.

But why not leaving it to the user? It's just one click: Kvantum Manager → Configure Active Themes → Hacks → Iconless menus. We also could set `iconless_menu` to `true` in KvArc. No hassle, no enforcement...

**Comment by CDrummond** [comment]
Because as a user - I just want a theme to work! Having to configure it is too much hassle. Perhaps there should be a config option - respect DE settings. Set to true by default. This allows to have sensible defaults, and for these to be overridden,

**Comment by tsujan** [comment]
> Perhaps there should be a config option - respect DE settings.

This is a great idea! It's good with KDE too. I'll add such an option soon :)

**Comment by tsujan** [comment]
Now that DE detection is fully implemented, shouldn't I also disable compositing under GTK-based DEs? This would solve Unity's double shadows.

**Pull request merged**
