### PR TITLE
Alter colours and spacing to be more Ambiance like

### PR DESCRIPTION
**Pull request by CDrummond**

### CODE REVIEW

**Comment by tsujan** [comment]
You know Ambiance better than I do but aren't `layout_spacing` and `layout_margin` too large here? They don't waste any space because Ambiance's text margins are small compared to most GTK themes but isn't a 9px `layout_margin` too big?

I'm sure that `text.press.color` and `text.toggle.color` shouldn't be #dfdbd2 under `[ItemView]`. I think you would prefer #fcfcfc for them.

**Comment by tsujan** [comment]
I'd chosen #000000d2 for better anti-aliasing but, again, you're more familiar with Ambiance that I am.

**Comment by CDrummond** [comment]
On Thu, 7 Sep, 2017 at 9:11 PM, tsujan <notifications@github.com> wrote:
> You know Ambiance better than I do but aren't layout_spacing and 
> layout_margin too large here? They don't waste any space because 
> Ambiance's text margins are small compared to most GTK themes but 
> isn't a 9px layout_margin too big?
> 
Just checked with Rhythmbox - and 9 is much better than 4
> I'm sure that text.press.color and text.toggle.color shouldn't be 
> #dfdbd2 under [ItemView]. I think you would prefer #fcfcfc for them.
> 
I've changed these to #fcfcfc as I think you're right - although I have 
no idea what they're for.

**Comment by CDrummond** [comment]
On Thu, 7 Sep, 2017 at 9:15 PM, tsujan <notifications@github.com> wrote:
> I'd chosen #000000d2 for better anti-aliasing but, again, you're more 
> familiar with Ambiance that I am.
> 

Can't see much difference with the AA. But #000000d2  produces a 
blacker text than Ambiance uses.

**Comment by tsujan** [comment]
> Just checked with Rhythmbox - and 9 is much better than 4

OK. Please compare it with other GTK apps too -- I lost my Ubuntu installed on VirtualBox; might install the new version in autumn.

> ... although I have no idea what they're for.

They're for selected view-items when an active and inactive window.

**Comment by CDrummond** [comment]
Still think the settings are better. Looked at shotwell, character map, and some others.

I'll give you some can be very cramped, others not. For me the settings in this pull request reflect the better end of the range.

Also. When Gtk apps do not have focus, the toolbar and buttons, etc, loose the gradient - and become flat. Does Kvantum support this?

**Comment by tsujan** [comment]
> Also. When Gtk apps do not have focus, the toolbar and buttons, etc, loose the gradient - and become flat. Does Kvantum support this?

Oh, yes! I'll implement that soon.

I want to merge this PR. Is it complete?

**Comment by tsujan** [comment]
By implementing I meant in KvAmbiance -- Kvantum supports inactive elements for a long time.

**Comment by CDrummond** [comment]
I think so

**Pull request merged**
