### PR TITLE
Convert INSTALL to markdown

### PR DESCRIPTION
**Pull request by krisives**
This makes it much easier for people to read on GitHub.

### CODE REVIEW

**Comment by tsujan** [comment]
Good idea!

**Comment by tsujan** [comment]
`~` inside ` '~/.config/Kvantum/$THEME_NAME/'` and similar strings is interpreted as strikethrough by github.

**Comment by tsujan** [comment]
Another problem exists in sub-sections: `##` should be used for them, instead of `#`.

**Comment by krisives** [comment]
I agree this can be fixed I'll spend a bit more time on in soon.

**Comment by tsujan** [comment]
Take your time.

`~` isn't really a markdown thing but github and some other sites use it for strikethrough.

**Comment by tsujan** [comment]
Merging... I'll take care of details soon -- might also change some parts a little.

Thanks for the idea and also for the PR!

**Pull request merged**
