### PR TITLE
Requested Changes

### PR DESCRIPTION
**Pull request by now-im**

### CODE REVIEW

**Comment by omni6** [comment]
Please not Yaourt!! Yaourt is not recommended, some people even say it is dangerous. If you need to suggest an aur helper why not an up-to-date like `trizen` or `yay`?

**Comment by tsujan** [comment]
We don't want to recommend anything but just to give an example. There's no need to another PR -- I'll edit the text and remove the Arch folders soon. Thanks!

**Comment by omni6** [comment]
Best would be if you simply link the aur page, arch users should know how to install.

**Comment by tsujan** [comment]
>  arch users should know how to install.

Exactly! Yaourt is just an example and Arch doc is the best -- so good that, when I was a Debian user, I solved my problems by consulting Arch pages. If I replace Yaourt with another AUR-helper, some people might say similar things ;)

**Comment by now-im** [comment]
I don't use yaourt either. However, this is still the most common known reference.

**Pull request merged**
