### PR TITLE
Added [it]

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
BTW, how about add Kvantum to weblate?

**Comment by tsujan** [comment]
> BTW, how about add Kvantum to weblate?

It was added by Alf and there were lots of Weblate translations. I don't know how to re-add it.

**Comment by stefonarch** [comment]
> It was added by Alf and there were lots of Weblate translations. I don't know how to re-add it.

You could have mentioned it ;)
I just did not think of it. [Added](https://translate.lxqt-project.org/projects/tsujan/).

**Comment by tsujan** [comment]
Thanks!

I thought something might be different about it and didn't want to bother you with it.

**Pull request merged**
