### PR TITLE
Add QProxyStyle support

### LINKED ISSUE #148: Is dolphin supposed to work with a transparent theme outside KDE5?
Hi, 
Is dolphin supposed to work with a transparent theme outside KDE5? Its background is not transparent on compiz0.8. But I tried [some dirty hack on  kvantum-qt5 0.10.4-1](https://github.com/tsujan/Kvantum/files/1236780/diff.txt) to make it work. 

Screenshots for pcman-qt, kate and dolphin
Before 
before
After
after

### PR DESCRIPTION
**Pull request by ShayBox**
Credit to trialuser02 at https://sourceforge.net/p/qt5ct/tickets/65/
Tested, fixes #148

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks! Please, instead, try this with qt5ct and tell me about result:
```c++
  if (qobject_cast<QProxyStyle *>(ws))
      ws = qobject_cast<QProxyStyle *>(ws)->baseStyle();
```
If the result is the same, I should first make sure there isn't any side effect.

**Comment by ShayBox** [comment]
Where would I put that, I know enough to copy paste code but I don't understand either of these code bases.

**Comment by tsujan** [comment]
Replace this in your PR with it and recompile/install Kvantum again:
```c++
  if(ws && ws->inherits("QProxyStyle"))
  {
      ws = qobject_cast<QProxyStyle *>(ws)->baseStyle();
  }
```
It's the same but safer.

**Comment by ShayBox** [comment]
Oh alright, I thought you meant put that in qt5ct, I see what you mean.

**Comment by ShayBox** [comment]
Tested the changes, it works aswell

**Comment by tsujan** [comment]
OK. Tomorrow, I'll hunt for possible side effects. If I find none, I'll merge this.

**Comment by tsujan** [comment]
Didn't find any problem.

**Pull request merged**
