### PR TITLE
Copy slider focus rect from KvAmbiance to KvCommunitheme

### PR DESCRIPTION
**Pull request by CDrummond**
I've copied the focus SVG from KvAmbiance. This (IMVHO) looks nicer, no?

### CODE REVIEW

**Comment by tsujan** [comment]
I didn't use the generic focus rect because it wasn't visible on a selected row of an item view -- while the dotted rect was. There are 2 kinds of focus rects in Kvantum: the generic one and the widget-specific ones. The second kind of rects is only for button-like widgets, sliders and tabs for now. Here, you used the first one, which is always rectangular and is shared between all widgets for which `focusFrame` is `false`. The widget-specific focus rect of sliders is chosen in the way you saw for a reason not related to this.

But if you like that rectangle, I may be able to extend the widget-specific rect to view-items and add a suitable rect for them to the SVG file.

**Comment by CDrummond** [comment]
Ah! Yeah, I just don't like the focus rect on the slider being just on the groove border - not very noticeable.

Can a view not have 1 focus for unselected items, and a different (highlighted text colour) for selected items?

**Comment by CDrummond** [comment]
Well, I'm sure QtCurve used a highlighted-text colour focus (underline) for selected items, and highlight colour for unselected items. So, it can be done. But, I guess you are saying its too much for Kvantum? As in too invasive a change? I could look into how it was done with QtCurve and try to do something similar?

**Comment by tsujan** [comment]
No, they're very different from each other. I'll take a look into QtCurve's code now.

**Comment by tsujan** [comment]
QtCurve doesn't handle `CE_ItemViewItem` at all :) As I'd suspected....

The problem is that there's no real problem. You want a focus rect similar to that of Communitheme and it simply isn't possible with Kvantum. IMHO, the current focus rect is quite visible and if more visibility is important to you, we could replace it with a dotted one. What do you choose?

**Comment by tsujan** [comment]
And please don't try to add an underline :) It wouldn't be compatible with how Kvantum does things.

**Comment by tsujan** [comment]
Ah, at last found a way to draw that widget-specific focus rect for item-views.... Will make a commit tomorrow.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/2e90621b26ca610bde9193b12a001f5379501e8c without touching the code. Playing with the orange was enough and the result is better than the above screenshots.

**Comment by CDrummond** [comment]
Thanks, will update later. BTW, I was not suggesting an underline - just describing how I thought it was implemented.

**Comment by tsujan** [comment]
Sorry that I thought so; I was confused about the code. My confusion was caused by a silly mistake but later, I saw there was no need to any change :)

**Comment by CDrummond** [comment]
Can I make one slight suggestion? Can the view focus rect be 1px offset from the outside edge? This way you will have 1px highlight, 1px focus, then the highlight itself. This should make it clearer.

**Comment by tsujan** [comment]
You mean the slider focus rect? It can't be outside the widget rect (actually, it can but with an enormous amount of dirty code) and it'll intersect the slider/handle/tick-marks in a very ugly way if it's inside the widget rect -- even with a 1-pix offset.

Interestingly, it seems that other styles don't draw it at all.

If you mean the view-item focus rect, it *is* inside the frame but  hard-coded styles of some apps may draw it wrongly on the frame.

**Comment by tsujan** [comment]
BTW, the more I use this theme, the more I like it; didn't like it at first.

**Comment by tsujan** [comment]
> Yeah, I was talking about view focus. You are correct though - I think in this case Cantata is at fault :-(

I know what you see. I've seen that in some KDE apps too. It seems that the code draws the focus rect on the border without consulting the style. If the focus rect is a dotted line, it's be visible in such cases too. Anyhow, I don't thinks it's worth changing Cantata's code because the focus rect doesn't have much use in such cases.

> Due to the view highlight, it looks as if there is larger gap on the sides than the top/bottom...

If you meant unequal gaps between the focus rect and the border, there isn't any here (magnify the image):

nogap

But if you mean the gap between the text and focus rect, a left text margin (right for RTL) can be added.

**Comment by CDrummond** [comment]
The thing with a Cantata's focus rects in views is odd, as I don't explicitly draw **any** focus rects. I just call `QStyledItemDelegate::paint(painter, option, index);` Do, not sure what's going on. 

As to the gap on the sides - as stated this was a visual affect of the view frame highlight being the same as the item highlight, making it **look** like there as a bigger gap. The gap was still 2px but the 2px + 1 px frame looks like 3px. But, as in your screenshot, the actual is fine.

In this screenshot you can see that the gap looks bigger on the left/right. It isn't actually bigger, jsut looks that way.

screenshot from 2018-04-04 08-46-32

Perhaps though, reduce the gap to just 1px? This would give more space before the text starts.

**Pull request closed without merging**
