### PR TITLE
Allow build on NetBSD

### PR DESCRIPTION
**Pull request by voidpin**
Hi,
And here I am again porting your software to NetBSD :)
This was a request from a user that I packaged yesterday, still a work-in-progress but, I hope to merge it the near future.

2020-04-16-100310_1366x768_scrot

Cheers!

### CODE REVIEW

**Comment by tsujan** [comment]
> still a work-in-progress

Take your time. Tell me when it's finished.

Thanks for adding NetBSD support to Kvantum!

**Comment by voidpin** [comment]
To be honest, I don't think I need to patch anything else. I'll have the user testing it and I will be looking for potential hard coded paths, NetBSD installs stuff to `/usr/pkg` and not `/usr` but, that you already know from previous discussions ;)

I'll let you know when its ready.

Also, we are in the process of importing **LXQt** desktop. The following are already imported and I'm using this on my own `spectrwm` development machine, `featherpad`, `lxqt-build-tools`, `libqtxdg`, `liblxqt`, `libfm-qt`, `pcmanfm-qt`, `qtermwidget`, `qterminal` and `lximage-qt`. Also imported but, I don't use these for obvious reasons, are `obconf-qt` and `pavucontrol-qt`.

**Comment by voidpin** [comment]
@tsujan Done! No other patches are needed, feel free to merge.
One question though...
I see, `option(ENABLE_QT4 "Building Qt4 plugin." OFF)` but, kde4 directories are still installed.
Arch uses a post-install step, `rm -r ${pkgdir}/usr/share/kde4
Would you recommend this or, are you planning to clean-up the kde4 directories by the next release?

**Comment by tsujan** [comment]
> I see, option(ENABLE_QT4 "Building Qt4 plugin." OFF) but, kde4 directories are still installed.

I'll look into it. Most probably, I forgot it and no one told me about it -- until now :) Thanks!

**Comment by voidpin** [comment]
@tsujan FYI, `kvantum` imported into pkgsrc, https://mail-index.netbsd.org/pkgsrc-changes/2020/04/19/msg211094.html

**Comment by tsujan** [comment]
@voidpin, thank you very much for your work!

Sorry for the delay; I've been extremely busy with code related jobs. I'll review and merge this PR soon.

**Comment by voidpin** [comment]
Thanks!

**Comment by tsujan** [comment]
I removed old KDE4 stuff at last, although Qt4 installation is still possible.

**Comment by voidpin** [comment]
@tsujan Awesome! I'll be waiting for the new release :)

**Comment by tsujan** [comment]
I'll release 0.15.3 soon, because of the fix for a "problem" no one encounters ;)

Have reserved V1.0.0 for when Qt6 comes out -- of course, if Qt devs don't make Qt closed-source until then (they've started to say [irrational things](https://www.phoronix.com/scan.php?page=news_item&px=Qt-Might-Restrict-New-Releases) because of coronavirus; I didn't know coronavirus could affect brains) -- but there might be other releases before that.

**Comment by voidpin** [comment]
No rush! I still have to package `screengrab` and `lxqt-archiever` for the `lxqt-0.15.0` release in NetBSD. Although, I'm considering shipping with `arqiver` instead, it shows in the default menu and its already packaged and available.

As for Qt going closed source, wasn't that just for the lts release? Not good in anycase though..

**Comment by tsujan** [comment]
I'll also make releases for Arqiver and lxqt-archiver in 2-3 weeks.

> As for Qt going closed source, wasn't that just for the lts release?

It was but now they say, because of coronavirus, blah blah blah.... as if coronavirus is only for them. In the end, I don't think anything bad will happen but, in the 21st century, irrationality has become so popular; so, who knows?

**Comment by voidpin** [comment]
I'll keep an eye on those, thanks.
Let's see what Qt does, a **lot of people** won't be happy.

**Pull request merged**
