### PR TITLE
Include my Copr Repository Pacakges for Fedora in INSTALL.md

### PR DESCRIPTION
**Pull request by ashahir05**
I have built packages for Fedora. If you want you can include those packages in INSTALL.md.

### CODE REVIEW

**Comment by tsujan** [comment]
Why not? Thanks :)

**Comment by ashahir05** [comment]
Hey @tsujan ? The "Kvantum" need to be changed to be "kvantum". So it would be nice if you did that.

**Comment by tsujan** [comment]
> The "Kvantum" need to be changed to be "kvantum"

I'll change it.

**Comment by ashahir05** [comment]
@tsujan The packages are in the official Fedora repository. There is no need to do this, so kindly remove this part:
```
sudo dnf copr enable ashahir05/kvantum

```

That is all that needs to be done by a user:
```
sudo dnf install kvantum
```

**Comment by tsujan** [comment]
Will do it tonight.

**Pull request merged**
