### PR TITLE
If group box has no frame, then left-align label

### PR DESCRIPTION
**Pull request by CDrummond**

### CODE REVIEW

**Comment by tsujan** [comment]
Why not putting label above frame (groupbox_top_label=true) and removing the frame (frame=false)? It would have the same effect without changing the code:

groupbox

**Comment by CDrummond** [comment]
I agree, it was more tying up a loose end. As in if there is no frame, it
looked odd having the text indented. No big issue really...

**Comment by tsujan** [comment]
Thanks! So, should I do it in KvArc instead? With the layout margin you added to it, it looks better:

cantata1

**Comment by CDrummond** [comment]
I guess to be consistent. But I do like the current look...

**Comment by tsujan** [comment]
Done at https://github.com/tsujan/Kvantum/commit/66af98891b39745b58acf159b4f48a549a1360c1.

**Pull request closed without merging**
